apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager-eu-central-1
    kind: ClusterSecretStore
  target:
    name: oauth2-proxy-auth
  data:
  - secretKey: client-id
    remoteRef:
      key: eks-gamesa/oauth2-proxy-auth
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: eks-gamesa/oauth2-proxy-auth
      property: client-secret
  - secretKey: cookie-secret
    remoteRef:
      key: eks-gamesa/oauth2-proxy-auth
      property: cookie-secret