apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
spec:
  releaseName: oauth2-proxy
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      version: ">=7.1.0"
  interval: 1m0s
  install:
    remediation:
      retries: 3
