apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mosquitto
  labels:
    app.kubernetes.io/xo-managed: false
spec:
  releaseName: mosquitto
  chart:
    spec:
      chart: mosquitto
      version: 4.x.x
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
  interval: 5m
  install:
    remediation:
      retries: 3
